export const GangData = [
  {title: 'Gang 01', value: 'Gang 01'},
  {title: 'Gang 02', value: 'Gang 02'},
  {title: 'Gang 03', value: 'Gang 03'},
];

export const RoData = [
  {
    roNumber: 'RO123',
    pendingQuantity: '100.00',
    commodity: 'Raw Rice',
    variety: 'Grade A',
    token: '1111',
    transactionType: 'Issue',
    maxBagsForTruck: '1000',
    cropYear: '2015-16',
    stack: 'Stack 11',
    shed: 'Shed 1',
    bagType: 'SBT',
    bags: '200',
    tareWeight: '400',
  },
  {
    roNumber: 'RO124',
    pendingQuantity: '200.00',
    commodity: 'Wheat',
    variety: 'Grade B',
    token: '1112',
    transactionType: 'Issue',
    maxBagsForTruck: '900',
    cropYear: '2016-17',
    stack: 'Stack 12',
    shed: 'Shed 3',
    bagType: 'SBT',
    bags: '300',
    tareWeight: '400',
  },
  {
    roNumber: 'RO125',
    pendingQuantity: '100.00',
    commodity: 'Raw Rice',
    variety: 'Grade A',
    token: '1113',
    transactionType: 'Issue',
    maxBagsForTruck: '850',
    cropYear: '2016-17',
    stack: 'Stack 12',
    shed: 'Shed 3',
    bagType: 'SBT',
    bags: '300',
    tareWeight: '400',
  },
  {
    roNumber: 'RO126',
    pendingQuantity: '250.00',
    commodity: 'Wheat',
    variety: 'Grade B',
    token: '1114',
    transactionType: 'Issue',
    maxBagsForTruck: '1000',
    cropYear: '2022-23',
    stack: 'Stack 5',
    shed: 'Shed 1',
    bagType: 'SBT',
    bags: '250',
    tareWeight: '350',
  },
  {
    roNumber: 'RO127',
    pendingQuantity: '300.00',
    commodity: 'Raw Rice',
    variety: 'Grade A',
    token: '1115',
    transactionType: 'Issue',
    maxBagsForTruck: '600',
    cropYear: '2021-22',
    stack: 'Stack 8',
    shed: 'Shed 4',
    bagType: 'SBT',
    bags: '450',
    tareWeight: '500',
  },
  {
    roNumber: 'RO128',
    pendingQuantity: '120.00',
    commodity: 'Wheat',
    variety: 'Grade B',
    token: '1116',
    transactionType: 'Issue',
    maxBagsForTruck: '1200',
    cropYear: '2023-24',
    stack: 'Stack 10',
    shed: 'Shed 2',
    bagType: 'SBT',
    bags: '350',
    tareWeight: '420',
  },
];

export const ActivityData = [
  {title: 'Activity 01', value: 'Activity 01'},
  {title: 'Activity 02', value: 'Activity 02'},
  {title: 'Activity 03', value: 'Activity 03'},
];

export const ShedData = [
  {title: 'Shed 01', value: 'Shed 01'},
  {title: 'Shed 02', value: 'Shed 02'},
  {title: 'Shed 03', value: 'Shed 03'},
];

export const GangListData = [
  {
    title: 'Gang No: 01',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Activity', editable: true},
      {title: 'Start Time', editable: true},
      {title: 'End Time', editable: true},
      {title: 'No of Bags', editable: false},
      {title: 'Labour Gang', editable: false},
      {title: 'Lead', editable: false},
      {title: 'Stack Name', editable: false},
    ],
    id: '1',
    checked: false,
  },
  {
    title: 'Gang No: 02',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Activity', editable: true},
      {title: 'Start Time', editable: true},
      {title: 'End Time', editable: true},
      {title: 'No of Bags', editable: false},
      {title: 'Labour Gang', editable: false},
    ],
    id: '2',
    checked: false,
  },
  {
    title: 'Gang No: 03',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Activity', editable: true},
      {title: 'Start Time', editable: true},
      {title: 'End Time', editable: true},
      {title: 'No of Bags', editable: false},
      {title: 'Labour Gang', editable: false},
    ],
    id: '3',
    checked: false,
  },
];

export const TokenData = [
  {title: 'Token 01', value: 'Token 01'},
  {title: 'Token 02', value: 'Token 02'},
  {title: 'Token 03', value: 'Token 03'},
];

export const ReferenceNumberData = [
  {title: 'RefTn72Bv9099', value: 'RefTn72Bv9099'},
  {title: 'RefTn72Bw0600', value: 'RefTn72Bw0600'},
  {title: 'RefTn72CZ0006', value: 'RefTn72CZ0006'},
];

export const OperationData = [
  {title: 'Operation 01', value: 'Operation 01'},
  {title: 'Operation 02', value: 'Operation 02'},
  {title: 'Operation 03', value: 'Operation 03'},
];

export const WagonListData = [
  {
    title: 'wagon 01',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Truck Number', editable: true},
      {title: 'Transaction Type', editable: true},
      {title: 'No of Bags', editable: true},
      {title: 'Commodity', editable: false},
      {title: 'Variety', editable: false},
    ],
    id: '1',
  },
  {
    title: 'wagon 02',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Truck Number', editable: true},
      {title: 'Transaction Type', editable: true},
      {title: 'No of Bags', editable: true},
      {title: 'Commodity', editable: false},
      {title: 'Variety', editable: false},
    ],
    id: '2',
  },
  {
    title: 'wagon 03',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Truck Number', editable: true},
      {title: 'Transaction Type', editable: true},
      {title: 'No of Bags', editable: true},
      {title: 'Commodity', editable: false},
      {title: 'Variety', editable: false},
    ],
    id: '3',
  },
];

export const LabourData = [
  {title: 'Labour 01', value: 'Labour 01'},
  {title: 'Labour 02', value: 'Labour 02'},
  {title: 'Labour 03', value: 'Labour 03'},
];

export const colorsTypeData = [
  {colors: '#F44336', value: 'Full'},
  {colors: '#00897b', value: '<60% and >0%'},
  {colors: '#004d40', value: '>=60% and <100%'},
  {colors: '#4A4A4A', value: 'Empty'},
];

export const ListData = [
  {
    title: 'wagon 01',
    icons: ['angle-down'],
    dropDownValues: [
      {title: 'Truck Number', editable: true},
      {title: 'Transaction Type', editable: true},
      {title: 'No of Bags', editable: true},
      {title: 'Commodity', editable: false},
      {title: 'Variety', editable: false},
    ],
    id: '1',
    checked: true,
  },
  {
    title: 'wagon 02',
    icons: ['angle-down'],
    dropDownValues: [
      {title: 'Truck Number', editable: true},
      {title: 'Transaction Type', editable: true},
      {title: 'No of Bags', editable: true},
      {title: 'Commodity', editable: false},
      {title: 'Variety', editable: false},
    ],
    id: '2',
    checked: false,
  },
  {
    title: 'wagon 03',
    icons: ['angle-down'],
    dropDownValues: [
      {title: 'Truck Number', editable: true},
      {title: 'Transaction Type', editable: true},
      {title: 'No of Bags', editable: true},
      {title: 'Commodity', editable: false},
      {title: 'Variety', editable: false},
    ],
    id: '3',
    checked: false,
  },
];

export const TemporaryStorageData = [
  {
    title: 'Shed 01',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Storage Type', editable: true},
      {title: 'Assigned Bags', editable: true},
      {title: 'Capacity (MT)', editable: true},
      {title: 'Max Bags', editable: false},
      {title: 'Lead', editable: false},
      {title: 'Bags Per Layer', editable: false},
      {title: 'Location Description', editable: false},
      {title: 'Comment', editable: false},
    ],
    id: '1',
    checked: false,
  },
  {
    title: 'Shed 02',
    icons: ['edit', 'trash-alt', 'angle-down'],
    dropDownValues: [
      {title: 'Storage Type', editable: true},
      {title: 'Assigned Bags', editable: true},
      {title: 'Capacity (MT)', editable: true},
      {title: 'Max Bags', editable: false},
      {title: 'Lead', editable: false},
      {title: 'Bags Per Layer', editable: false},
      {title: 'Location Description', editable: false},
      {title: 'Comment', editable: false},
    ],
    id: '2',
    checked: false,
  },
];

export const ShedData1 = [
  {
    id: '1',
    title: 'shed 1',
    iconName: 'warehouse',
    progress: 1,
    color: '#F44336',
    stackCount: 8,
  },
  {
    id: '2',
    title: 'shed 2',
    iconName: 'warehouse',
    progress: 0,
    color: '#4A4A4A',
    stackCount: 3,
  },
  {
    id: '3',
    title: 'shed 3',
    iconName: 'warehouse',
    progress: 0.8,
    color: '#004d40',
    stackCount: 5,
  },
  {
    id: '4',
    title: 'shed 4',
    iconName: 'warehouse',
    progress: 0.4,
    color: '#00897b',
    stackCount: 10,
  },
  {
    id: '5',
    title: 'shed 5',
    iconName: 'warehouse',
    progress: 0.8,
    color: '#004d40',
    stackCount: 5,
  },
  {
    id: '6',
    title: 'shed 6',
    iconName: 'warehouse',
    progress: 0,
    color: '#4A4A4A',
    stackCount: 1,
  },
  {
    id: '7',
    title: 'shed 7',
    iconName: 'warehouse',
    progress: 0.25,
    color: '#00897b',
    stackCount: 5,
  },
  {
    id: '8',
    title: 'shed 8',
    iconName: 'warehouse',
    progress: 0.6,
    color: '#004d40',
    stackCount: 2,
  },
  {
    id: '9',
    title: 'shed 9',
    iconName: 'warehouse',
    progress: 0,
    color: '#4A4A4A',
    stackCount: 5,
  },
  {
    id: '10',
    title: 'shed 10',
    iconName: 'warehouse',
    progress: 0.35,
    color: '#00897b',
    stackCount: 8,
  },
  {
    id: '11',
    title: 'shed 11',
    iconName: 'warehouse',
    progress: 0.45,
    color: '#00897b',
    stackCount: 6,
  },
  {
    id: '12',
    title: 'shed 12',
    iconName: 'warehouse',
    progress: 0.75,
    color: '#004d40',
    stackCount: 5,
  },
  {
    id: '13',
    title: 'shed 13',
    iconName: 'warehouse',
    progress: 0.9,
    color: '#004d40',
    stackCount: 9,
  },
  {
    id: '14',
    title: 'shed 14',
    iconName: 'warehouse',
    progress: 1,
    color: '#F44336',
    stackCount: 5,
  },
];

export const StackData = [
  {
    id: '1',
    title: 'Stack 1',
    capacity: '100 Qtls',
    stackName: '1A001',
    utilization: '77%',
    cropYear: '2014-15',
    color: '#004d40',
  },
  {
    id: '2',
    title: 'Stack 2',
    capacity: '80 Qtls',
    stackName: '2A001',
    utilization: '100%',
    cropYear: '2014-15',
    color: '#F44336',
  },
  {
    id: '3',
    title: 'Stack 3',
    capacity: '100 Qtls',
    stackName: '3A001',
    utilization: '0%',
    cropYear: '2015-16',
    color: '#4A4A4A',
  },
  {
    id: '4',
    title: 'Stack 4',
    capacity: '80 Qtls',
    stackName: '4A001',
    utilization: '30%',
    cropYear: '2017-18',
    color: '#00897b',
  },
  {
    id: '5',
    title: 'Stack 5',
    capacity: '100 Qtls',
    stackName: '5A001',
    utilization: '65%',
    cropYear: '2014-15',
    color: '#004d40',
  },
  {
    id: '6',
    title: 'Stack 6',
    capacity: '80 Qtls',
    stackName: '6A001',
    utilization: '100%',
    cropYear: '2019-20',
    color: '#F44336',
  },
  {
    id: '7',
    title: 'Stack 7',
    capacity: '100 Qtls',
    stackName: '7A001',
    utilization: '70%',
    cropYear: '2015-16',
    color: '#004d40',
  },
  {
    id: '8',
    title: 'Stack 8',
    capacity: '80 Qtls',
    stackName: '8A001',
    utilization: '50%',
    cropYear: '2017-18',
    color: '#004d40',
  },
  {
    id: '9',
    title: 'Stack 9',
    capacity: '40 Qtls',
    stackName: '9A001',
    utilization: '20%',
    cropYear: '2015-16',
    color: '#00897b',
  },
  {
    id: '10',
    title: 'Stack 10',
    capacity: '70 Qtls',
    stackName: '10A001',
    utilization: '50%',
    cropYear: '2017-18',
    color: '#004d40',
  },
  {
    id: '11',
    title: 'Stack 11',
    capacity: '100 Qtls',
    stackName: '11A001',
    utilization: '90%',
    cropYear: '2014-15',
    color: '#004d40',
  },
  {
    id: '12',
    title: 'Stack 12',
    capacity: '80 Qtls',
    stackName: '12A001',
    utilization: '100%',
    cropYear: '2019-20',
    color: '#F44336',
  },
  {
    id: '13',
    title: 'Stack 13',
    capacity: '20 Qtls',
    stackName: '13A001',
    utilization: '50%',
    cropYear: '2014-15',
    color: '#004d40',
  },
  {
    id: '14',
    title: 'Stack 14',
    capacity: '100 Qtls',
    stackName: '14A001',
    utilization: '0%',
    cropYear: '2015-16',
    color: '#4A4A4A',
  },
  {
    id: '15',
    title: 'Stack 15',
    capacity: '80 Qtls',
    stackName: '15A001',
    utilization: '50%',
    cropYear: '2018-19',
    color: '#004d40',
  },
];

export const outWeightData = [
  {
    tokenNumber: '1101',
    commodity: 'Wheat',
    cropYear: '2024',
    bagType: 'SBT',
    noOfBags: 100,
    shed: 'Shed A',
    stack: 'Stack 3',
    truckWeight: '2500 kg',
    tareWeightInQtls: 10,
    tareWeight: 100,
    emptyBagsWeightInQtls: 2,
    netWeightInQtls: 98,
  },
  {
    tokenNumber: '1102',
    commodity: 'Rice',
    cropYear: '2023',
    bagType: 'SBT',
    noOfBags: 150,
    shed: 'Shed B',
    stack: 'Stack 2',
    truckWeight: '2800 kg',
    tareWeightInQtls: 12,
    tareWeight: 120,
    emptyBagsWeightInQtls: 3,
    netWeightInQtls: 117,
  },
  {
    tokenNumber: '1103',
    commodity: 'Wheat',
    cropYear: '2022',
    bagType: 'SBT',
    noOfBags: 80,
    shed: 'Shed C',
    stack: 'Stack 5',
    truckWeight: '2400 kg',
    tareWeightInQtls: 8,
    tareWeight: 90,
    emptyBagsWeightInQtls: 1,
    netWeightInQtls: 89,
  },
  {
    tokenNumber: '1104',
    commodity: 'Whaeat',
    cropYear: '2024',
    bagType: 'SBT',
    noOfBags: 120,
    shed: 'Shed D',
    stack: 'Stack 1',
    truckWeight: '2600 kg',
    tareWeightInQtls: 9,
    tareWeight: 110,
    emptyBagsWeightInQtls: 2,
    netWeightInQtls: 108,
  },
];

export const PriorityList = [
  {
    checked: true,
    id: '1',
    title: '1A00994',
    icons: ['1'],
    dropDownValues: [
      {title: 'Priority', editable: false},
      {title: 'Shed', editable: false},
      {title: 'CropYear', editable: false},
      {title: 'BagType', editable: false},
      {title: 'Category', editable: false},
      {title: 'Specification', editable: false},
      {title: 'Available_Quantity', editable: false},
      {title: 'Available_Bags', editable: false},
      {title: 'Assigned Bags', editable: true},
    ],
  },
  {
    checked: false,
    id: '2',
    title: '1A00995',
    icons: ['1'],
    dropDownValues: [
      {title: 'Priority', editable: false},
      {title: 'Shed', editable: false},
      {title: 'CropYear', editable: false},
      {title: 'BagType', editable: false},
      {title: 'Category', editable: false},
      {title: 'Specification', editable: false},
      {title: 'Available_Quantity', editable: false},
      {title: 'Available_Bags', editable: false},
      {title: 'Assigned Bags', editable: true},
    ],
  },
  {
    checked: false,

    id: '3',
    title: '1A00996',
    icons: ['1'],
    dropDownValues: [
      {title: 'Priority', editable: false},
      {title: 'Shed', editable: false},
      {title: 'CropYear', editable: false},
      {title: 'BagType', editable: false},
      {title: 'Category', editable: false},
      {title: 'Specification', editable: false},
      {title: 'Available_Quantity', editable: false},
      {title: 'Available_Bags', editable: false},
      {title: 'Assigned Bags', editable: true},
    ],
  },
];
