export const ROData = [
  {
    tokenNumber: 'Token 1',
    truckNumber: 'Tn 72 BW 9099',
    values: {
      dropDown: [{title: 'Token 1', value: 'Token 1'}],
    },
    transactionType: 'Issue',
    noOfBags: 20,
    cropYear: '2014-15',
    bagType: 'SBT',
    commodity: 'Raw Rice',
    variety: 'Grade A',
    roNumber: 'Ro Number 1',
    pendingQuantity: 500,
    maxBagsForthisTruck: 50,
    operationCompleted: ['Issue Gate Pass'],
    priorityList: [
      {
        checked: true,
        id: '1',
        title: '1A00994',
        icons: ['1'],
        dropDownValues: [
          {title: 'Priority', editable: true},
          {title: 'Shed', editable: false},
          {title: 'CropYear', editable: false},
          {title: 'BagType', editable: false},
          {title: 'Category', editable: false},
          {title: 'Specification', editable: false},
          {title: 'Available_Quantity', editable: false},
          {title: 'Available_Bags', editable: false},
        ],
      },
      {
        checked: false,
        id: '2',
        title: '1A00995',
        icons: ['1'],
        dropDownValues: [
          {title: 'Priority', editable: true},
          {title: 'Shed', editable: true},
          {title: 'CropYear', editable: false},
          {title: 'BagType', editable: false},
          {title: 'Category', editable: false},
          {title: 'Specification', editable: false},
          {title: 'Available_Quantity', editable: false},
          {title: 'Available_Bags', editable: false},
        ],
      },
    ],
  },
  {
    tokenNumber: 'Token 2',
    truckNumber: 'Tn 72 BW 0600',
    values: {
      dropDown: [{title: 'Token 2', value: 'Token 2'}],
    },
    transactionType: 'Issue',
    noOfBags: 20,
    cropYear: '2014-15',
    bagType: 'SBT',
    commodity: 'Raw Rice',
    variety: 'Grade A',
    roNumber: 'Ro Number 1',
    pendingQuantity: 500,
    maxBagsForthisTruck: 50,
    operationCompleted: ['Issue Gate Pass', 'Capture In Weight'],
    priorityList: [
      {
        checked: true,
        id: '1',
        title: '1A00994',
        icons: ['1'],
        dropDownValues: [
          {title: 'Priority', editable: false},
          {title: 'Shed', editable: false},
          {title: 'CropYear', editable: false},
          {title: 'BagType', editable: false},
          {title: 'Category', editable: false},
          {title: 'Specification', editable: false},
          {title: 'Available_Quantity', editable: false},
          {title: 'Available_Bags', editable: false},
        ],
      },
      {
        checked: true,
        id: '2',
        title: '1A00995',
        icons: ['1'],
        dropDownValues: [
          {title: 'Priority', editable: false},
          {title: 'Shed', editable: false},
          {title: 'CropYear', editable: false},
          {title: 'BagType', editable: false},
          {title: 'Category', editable: false},
          {title: 'Specification', editable: false},
          {title: 'Available_Quantity', editable: false},
          {title: 'Available_Bags', editable: false},
        ],
      },
      {
        checked: false,
        id: '3',
        title: '1A00996',
        icons: ['1'],
        dropDownValues: [
          {title: 'Priority', editable: false},
          {title: 'Shed', editable: false},
          {title: 'CropYear', editable: false},
          {title: 'BagType', editable: false},
          {title: 'Category', editable: false},
          {title: 'Specification', editable: false},
          {title: 'Available_Quantity', editable: false},
          {title: 'Available_Bags', editable: false},
        ],
      },
    ],
  },
];
